### PR TITLE
straight line

### PR DESCRIPTION
**Pull request by dcooley**
I've had a go at implement a straight line for https://github.com/Awalz/SwiftyDraw/issues/4

I've made a public variable [`isStraight`](https://github.com/dcooley/SwiftyDraw/blob/master/Source/SwiftyDraw.swift#L72) 

```swift
/// sets whether the line drawn should be straight
public var isStraight = false
```

which, when set to `true` creates a straight line between the first touch point and the current point

```swift
lines.removeLast()
            
let newLine = Line(path: CGMutablePath(),
    brush: Brush(color: brush.color, width: brush.width, opacity: brush.opacity, blendMode: brush.blendMode))
newLine.path.addPath(createNewStraightPath())
lines.append(newLine)
drawingHistory = lines
```

Using the methods

```swift
    private func createNewStraightPath() -> CGMutablePath {
        let pt1 : CGPoint = firstPoint
        let pt2 : CGPoint = currentPoint
        let subPath = createStraightSubPath(pt1, mid2: pt2)
        let newPath = addSubPathToPath(subPath)
        return newPath
    }

    private func createStraightSubPath(_ mid1: CGPoint, mid2: CGPoint) -> CGMutablePath {
        let subpath : CGMutablePath = CGMutablePath()
        subpath.move(to: mid1)
        subpath.addLine(to: mid2)
        return subpath
    }

```

### CODE REVIEW

**Comment by LinusGeffarth** [comment]
Thanks for your contribution!
I will check it out the next days and merge if possible :)

**Comment by LinusGeffarth** [comment]
Hey, so I merged it, but as I tried it out, I saw the following result, when dragging in a circle:

IMG_26A3EB0B2D72-1

**Comment by dcooley** [comment]
yeah that's weird. I'll see if I can track it down.

**Comment by dcooley** [comment]
@LinusGeffarth  I've finally managed to get around to this, and I think the solution is to put a `setNeedsDisplay()` inside the `if shouldDrawStraight {` condition [here](https://github.com/Awalz/SwiftyDraw/blob/master/Source/SwiftyDraw.swift#L195)

```
        if shouldDrawStraight {
            lines.removeLast()
            setNeedsDisplay()   
            let newLine = Line(path: CGMutablePath(),
                               brush: Brush(color: brush.color, width: brush.width, opacity: brush.opacity, blendMode: brush.blendMode))
            newLine.path.addPath(createNewStraightPath())
            lines.append(newLine)
            drawingHistory = lines
        } else {
            let newPath = createNewPath()
            if let currentPath = lines.last {
                currentPath.path.addPath(newPath)
            }
        }
    }
```

Would you like me to make another PR, or are you happy to test and implement this yourself?

**Comment by LinusGeffarth** [comment]
Thanks. If you could open a PR, that'd be appreciated.

**Comment by dcooley** [comment]
done.

The other issue I was having was caused something else in my project, so I don't think there is anything else to be done.

**Comment by talaviram** [comment]
Is this still considered experimental after invalidating (`setNeedsDisplay()`)?
because the code still has a comment this is experimental.

**Comment by dcooley** [comment]
For what it's worth, I've not had any issues in the 3 months of using this feature.

**Pull request merged**
