### PR TITLE
Update Example to Swift 4.2

### PR DESCRIPTION
**Pull request by dylanshine**
Hey!

I like your library. I updated the example to 4.2, added a gitignore and tidied up a bit.

### CODE REVIEW

**Comment by LinusGeffarth** [comment]
Thanks for your contribution, I appreciate it.  
Please see the review comments. After you've pushed a new commit for that, I'll happily merge the PR.

**Comment by dylanshine** [comment]
@LinusGeffarth I don't see any comments on this PR

**Comment by LinusGeffarth** [comment]
@dylanshine 
I added code suggestions for lines 69-70.

**Comment by dylanshine** [comment]
@LinusGeffarth Idk if its a privacy setting but I can't see your suggestions

**Comment by LinusGeffarth** [comment]
I suggested:

    public var lines: [Line] = []
    public var drawingHistory: [Line] = []

**Comment by LinusGeffarth** [comment]
`line` should actually be `lines`

**Pull request merged**
